#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2
id = "ots"
name = "ots"
description.en = "One time secret sharing platform with symetric encryption in the browser"
description.fr = "Partage de mot de passe crypté dans le navigateur"
version = "1.21.5~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "Apache-2.0"
website = "https://ots.fyi/"
demo = "https://ots.fyi/"
admindoc = "https://github.com/Luzifer/ots/wiki"
code = "https://github.com/Luzifer/ots"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "200M"
ram.build = "500M"
ram.runtime = "500M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/ots"

    [install.init_main_permission]
    type = "group"
    default = "visitors"


[resources]
    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/Luzifer/ots/releases/download/v1.21.5/ots_linux_amd64.tgz"
    amd64.sha256 = "7be2782a01103a2dddf328e8004b2b2533265acd210eb4d1cccdc64342930bd7"
    arm64.url = "hhttps://github.com/Luzifer/ots/releases/download/v1.21.5/ots_linux_arm64.tgz"
    arm64.sha256 = "2ea956b87f8a244cc968de6dae380efe142cc880fc0e0cbdcdd39acf4d980230"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
	allow_email = true
    
    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
    
    [resources.apt]
    packages = "redis-server"
